### ISSUE TITLE
Implement a Vector2D class

### ISSUE THREAD

**Issue by dxu** [apophanystudios/pew#1]
with standard 2d vector operations

**Comment by likangning93** [comment]
might be worth looking at Cesium's Cartesian2 implementation for design
comparison and unit tests.

**Comment by dxu** [comment]
stawker

time to pull up 277 HW#1

**Comment by dxu** [comment]
@likangning93 https://github.com/AnalyticalGraphicsInc/cesium/blob/552c486c5dde9eed2c3e079378a362df13a9b31d/Source/Core/Cartesian2.js this, right?

**Comment by likangning93** [comment]
yeah. i guess more useful might be if you drift in to 3-vector territory
and 3x3 matrices. *shrug*

**Comment by dxu** [comment]
cool, thanks! I don't think I'll be needing the 3d vector classes.
